### PR TITLE
Improve shell script

### PR DESCRIPTION
**Pull request by alexey-zakharenkov**
Changes overview:

1) Stop `process_subways.sh` script if `osmupdate $PLANET` phase fails. Otherwise the rest of the script may work with corrupted planet file.

2) Rewrite a bash operator from `[ test ] && command` to `if [ test ]; then command; fi` because with the first syntax if the `test` fails then the whole script returns non-zero code which confuses encompassing script.

### CODE REVIEW

**Comment by alexey-zakharenkov** [comment]
I've just caught an unwanted behavior on storage exhaustion again: osmupdate failed but the validator continued running with corrupted planet. Made one more fix. PTAL.

**Comment by Zverik** [comment]
Yeah, looks good to me.

**Comment by alexey-zakharenkov** [comment]
Unfortunately, my effort didn't succeed since osmupdate tool doesn't conform POSIX exit code conventions and returns 0 at least on some types of errors, e.g. on lack of disk space: 
```
> ./osmupdate --drop-author --out-o5m planet.o5m planet.o5m.new.o5m
osmconvert Error: write error.
> echo $?
0
```

I freeze the pull request till I make the script stop on osmupdate failure. I assume analyzing stderr will do the trick.

**Comment by alexey-zakharenkov** [comment]
Please take a look now.

**Comment by vicpopov** [comment]
LGTM.
Different exit codes might be an overkill, but nothing bad with them.

**Pull request merged**
